### ISSUE TITLE
RODBC--> ODBC

### ISSUE THREAD

**Issue by GlennRDoherty** [rparrish/RPamisc#23]
Migrating Libraries from R 3.2 to R 3.3.1
RPamisc is dependent on ODBC package. 
package ‘ODBC’ is not available (for R version 3.3.1). RODBC is available for 3.3, but is no longer compatible with RPamisc. Do I need to manually install ODBC or is this a bug in RPamisc?
Thanks Rollie

**Comment by rparrish** [comment]
Not a bug - odbc package is new and a LOT faster. Just manually install the
'odbc' package.

# install.packages(devtools)devtools::install_github("rstats-db/odbc")


-- 
Rollie Parrish
rparrish@flightweb.com
